Update license header and extend pre-commit
eclipse-velocitas/license-check pull request #30
Opened 2023-11-28 12:18 UTC by kse3hi

ADO#17300

2023-12-07 09:44 UTC, mml5bg submitted a review, later dismissed
LGTM

2024-01-11 07:08 UTC, MP91 requested changes

2024-01-11 07:08 UTC, MP91 commented on .devcontainer/devcontainer.json
> -// ********************************************************************************/
why is this removed? can't we license this file?

2024-01-11 07:08 UTC, MP91 commented on setup.cfg
> +ignore_errors = True
is the ignoring of errors and missing imports a good idea? isn't that exactly what we want to find?

2024-01-11 07:08 UTC, MP91 commented on src/licensevalidator/lib/workflowlicenses.py
> +    request_headers = {"Accept": "application/vnd.github.v3+json"}
in all other project we force the space between the assignments, please adjust the settings accordingly

2024-01-11 10:58 UTC, MP91 approved these changes
lgtm

2024-01-11 10:59 UTC, merged